// <auto-generated />
using Entitystudent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Entitystudent.Migrations
{
    [DbContext(typeof(Studentcontext))]
    [Migration("20220719050452_studentmigrations")]
    partial class studentmigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Entitystudent.Model.Student", b =>
                {
                    b.Property<int>("rollnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("studentname")
                        .HasColumnType("text");

                    b.HasKey("rollnumber");

                    b.ToTable("student");
                });
#pragma warning restore 612, 618
        }
    }
}
